# Generated by Django 4.1.1 on 2023-06-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='current_player',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000015E9F2255D0>', max_length=100),
        ),
    ]
