# Generated by Django 4.1.1 on 2023-06-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_tictactoe_current_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='current_player',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001C2ED1B55D0>', max_length=100),
        ),
    ]
