# Generated by Django 4.1.1 on 2023-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_tictactoe_current_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='player',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
