# Generated by Django 4.2.2 on 2023-06-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_alter_tictactoe_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="tictactoe",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
